__author__ = 'alexdixon'
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibSeq=[1,2]
evenFib=[]

def evenFibSum():
    i = 2
    while fibSeq[-1] < 4000000:
        if fibSeq[-1] % 2 == 0:
            evenFib.append(fibSeq[-1])
        i += 1
        a_n = fibSeq.append(fibSeq[-2]+fibSeq[-1])
    else:
        return sum(evenFib)

print(evenFibSum())